# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       telepathy-haze

# >> macros
# << macros

Summary:    A multi-protocol Libpurple connection manager for Telepathy
Version:    0.8.0
Release:    1
Group:      Applications/Communications
License:    GPLv2+
URL:        http://developer.pidgin.im/wiki/Telepathy
Source0:    http://anongit.freedesktop.org/git/telepathy/%{name}.git/
Source100:  telepathy-haze.yaml
BuildRequires:  pkgconfig(purple)
BuildRequires:  pkgconfig(telepathy-glib)
BuildRequires:  pkgconfig(libxslt)
BuildRequires:  dbus-python
BuildRequires:  pygobject2
BuildRequires:  python-twisted

%description

telepathy-haze is a connection manager built around libpurple, the core of
Pidgin (formerly Gaim), as a Summer of Code project under the Pidgin umbrella.
Ultimately, any protocol supported by libpurple will be supported by
telepathy-haze; for now, XMPP, MSN and AIM are known to work acceptably, and
others will probably work too.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING NEWS
%{_libexecdir}/telepathy-haze
%{_datadir}/dbus-1/services/*.haze.service
%{_mandir}/man8/telepathy-haze.8*
# >> files
# << files
